#import './fragment/pagination-fragment.gql'
#import './fragment/user-fragment.gql'
query GetUsersGql($nickname: String, $page: Int, $pageSize: Int, $wechatId: String!, $tagId: Int){
    getUsers(nickname: $nickname, page: $page, pageSize: $pageSize, wechatId: $wechatId, tagId: $tagId){
      users{
        ...user
      },
      pagination {
        ...pagination
      }
    }
}

mutation UpdateUserTagGql($userId: String!, $tagid_list: [Int!]){
  updateUserTag(userId: $userId, tagid_list: $tagid_list)
}
